### PR TITLE
Add avtranscoder formula

### PR DESCRIPTION
**Pull request by cchampet**
Currently Mikros Image fork of the official repository.

### CODE REVIEW

**Comment by cbenhagen** [comment]
why do you use the fork?

**Comment by fabiencastan** [comment]
It seems nice to have one repository for all image/video processing libs, isn't it?
It would be nice to propose it to become an official repository on homebrew.

**Comment by cchampet** [comment]
@cbenhagen Currently the Mikros Image fork of AvTranscoder is more advanced. We will merge our work to the official AvTranscoder repository as soon as possible.

**Comment by cbenhagen** [comment]
@fabiencastan Unless we want to maintain ALL the image/video processing libs, I would rather put our formulae in the main homebrew repo. I think we should do this as soon as tuttleofx .9 is ready.

@cchampet ah ok i see

**Pull request merged**
